hr:
  salary:
    def:
      percent: 5
    smart:
      limit1: 1
      limit2: 2.5
      limit3: 5
      percent1: 1
      percent2: 2
      percent3: 5
      limits:
        1: 1
        2.5: 2
        5: 5
        10: 10
        7.5: 8 

logging:
  level:
    org.springframework.security: debug 

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr
    username: postgres
    password: postgres
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
#update vagy 
#lehet create is, akkor újragenerál mindent nulláról      
    open-in-view: true
#lehet false is, akkor csak a tranzakcióban nyitott a data session    
    
    
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

  profiles:
    active: smart

  thymeleaf:
    cache: false
